[versions]
logback = "1.3.14"
awssdkS3 = "2.40.13"
jackson = "2.20.1"
nettyHttpRouter = "1.15"
apacheCommonsCodec = "1.17.1"
netty = "4.2.9.Final"
apacheCommonsCollections4 = "4.5.0"
commonsIo = "2.21.0"
apacheCommonsLang3 = "3.20.0"
junit5 = "5.11.4"
mockito = "5.12.0"
lombok = "1.18.36"
slf4j = "2.0.17"
testContainers = "1.20.6"
apacheCommonsCompress = "1.28.0"
robothyCnRepo = "1.18"
gradleLombok = "5.0.0"

[libraries]
logbackClassic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
awssdkS3 = { group = "software.amazon.awssdk", name = "s3", version.ref = "awssdkS3" }
awssdkS3vectors = { group = "software.amazon.awssdk", name = "s3vectors", version.ref = "awssdkS3" }
awss3ApacheClient = { group = "software.amazon.awssdk", name = "apache-client", version.ref = "awssdkS3" }
jacksonDatabind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jacksonDataformatXml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-xml", version.ref = "jackson" }
jacksonDatatypeJdk8 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jdk8", version.ref = "jackson" }
jacksonDatatypeJsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson" }
nettyHttpRouter = { group = "io.github.robothy", name = "netty-http-router", version.ref = "nettyHttpRouter" }
apacheCommonsCodec = { group = "commons-codec", name = "commons-codec", version.ref = "apacheCommonsCodec" }
nettyAll = { group = "io.netty", name = "netty-all", version.ref = "netty" }
apacheCommonsCollections4 = { group = "org.apache.commons", name = "commons-collections4", version.ref = "apacheCommonsCollections4" }
commonsIo = { group = "commons-io", name = "commons-io", version.ref = "commonsIo" }
apacheCommonsLang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "apacheCommonsLang3" }
junit5 = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit5" }
junit5JupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }
#mockitoInline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockito" }
mockitoCore = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
slf4jApi = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
testContainers = { group = "org.testcontainers", name = "testcontainers", version.ref = "testContainers" }
testContainersJunit = { group = "org.testcontainers", name = "junit-jupiter", version.ref = "testContainers" }
apacheCommonsCompress = { group = "org.apache.commons", name = "commons-compress", version.ref = "apacheCommonsCompress" }
robothyCnRepo = { group = "com.robothy", name = "cn-repo", version.ref = "robothyCnRepo" }
gradleLombok = { group = "io.franzbecker", name = "gradle-lombok", version.ref = "gradleLombok" }
